### ISSUE TITLE
Parse not waiting for Mongo once .initialized file exists

### ISSUE THREAD

**Issue by robmacecs** [bitnami/bitnami-docker-parse-dashboard#37]
**Description**

The `.initialized` file created by nami seems to break the `depends_on` between parse and mongodb. 
First `up` works, but the next time, Parse will crash because the mongodb connection is unavailable. Checking the logs shows that mongodb "accepting connections" does indeed come second to the error.

**Steps to reproduce the issue:**

1. Download the docker-compose.yml from this repo as described
2. Add a persistent volume to the containers
```
    volumes:
      - './persistent:/bitnami'
```
3. `docker-compose up` 
4. `docker-compose down`
5. `docker-compose up`

**Describe the results you received:**

```
parse_1            | [30] parse-server running on http://127.0.0.1:1337/parse
parse_1            | warn: Unable to ensure uniqueness for usernames:  MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.19.0.2:27017]
```
followed by
```
mongodb_1          | 2019-02-23T17:33:03.006+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
```

If you delete the `.initialized` files in between stopping and restarting the containers, it works as expected `rm persistent/mongodb/.* persistent/parse/.* persistent/parse-dashboard/.*` 

**Describe the results you expected:**

Parse should still wait for MongoDb to be accepting connections, even when previously initialised. 

**Additional information you deem important (e.g. issue happens only occasionally):**

If you delete the `.initialized` files from the host persistent folder. The container dependencies work as expected again, so it seems pretty clear that the usage of `nami` is at fault. But I don't know if it's a problem with nami or with the way it's used in this repo? Is this the correct place for this issue? 

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 13
 Running: 2
 Paused: 0
 Stopped: 11
Images: 55
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.744GiB
Name: linuxkit-025000000001
ID: CTOH:GY7N:GG5G:HZKY:Z5GN:ZTRH:QAH3:BALO:IXWL:G4UG:72CK:36DA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 76
 System Time: 2019-02-23T17:38:30.724054585Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I launched the instance without mongodb (just for testing) and the container does not crash. It does show an error but it will not crash

```
preventLoginWithUnverifiedEmail: false
enableSingleSchemaCache: false
enableExpressErrorHandler: false
jsonLogs: false
verbose: false
level: undefined

[32] parse-server running on http://127.0.0.1:1337/parse
warn: Unable to ensure uniqueness for usernames:  MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
warn: Unable to ensure uniqueness for user email addresses:  MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
warn: Unable to ensure uniqueness for role name:  MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
(node:32) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:32) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

Could you confirm that you are using the latest version of the container?
